## Some math in python

Complete the code in the functions math1-math12 below.


In [5]:
import numpy as np


In [6]:
def math1(mat):
  """
  Square each value in mat separatly and return the result
  """
  return None

In [7]:
mat = np.arange(16).reshape((4, 4))
print(math1(mat))

None


### Expected output  
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [8]:
def math2(mat):
  """
  Return the sum of all the values in mat
  """
  return None


In [9]:
mat = np.arange(16).reshape((4, 4))
print(math2(mat))

None


### Expected output

120


In [10]:
def math3(mat):
  """
  Return the sum of each row in mat
  """
  return None

In [11]:
mat = np.arange(16).reshape((4, 4))
print(math3(mat)) 

None


### Expected output

[ 6 22 38 54]

In [12]:
def math4(mat):
  """
  Return a scaled version of mat, so that it sums to 1
  """
  return None


In [13]:
mat = np.arange(16).reshape((4, 4))
print(math4(mat))

None


### Expected output

[[ 0.          0.00833333  0.01666667  0.025     ]
 [ 0.03333333  0.04166667  0.05        0.05833333]
 [ 0.06666667  0.075       0.08333333  0.09166667]
 [ 0.1         0.10833333  0.11666667  0.125     ]]

In [14]:
def math5(mat, v):
  """
  Element-wise multiply each column in mat with vector v
  """
  return None

In [15]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math5(mat,vec))

None


### Expected output

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]

In [16]:
def math6(mat, v):
  """
  Element-wise multiply each row in mat with vector v
  """
  return None


In [17]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math6(mat,vec))

None


### Expected output

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]

In [18]:

def math7(mat, v):
  """
  Matrix multiply matrix m with vector v
  """
  return None

In [19]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math7(mat,vec))

None


### Expected output

[14 38 62 86]

In [22]:
def math8(mat):
  """
  Return the inverse matrix of mat
  """
  return None


In [23]:
mat = np.array([[4, 7], [2, 6]])
print(math8(mat))

None


### Expected output

[[ 0.6 -0.7]
 [-0.2  0.4]]
 

In [26]:
def math9(mat, v):
  """
  Return the dot-product between each row in mat and v
  """
  return None

In [27]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math9(mat,vec))

None


### Expected output

[14 38 62 86]

In [28]:
def math10(mat, v):
  """
  Return the dot-product between each column in mat and v
  """
  return None


In [29]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math10(mat,vec))

None


### Expected output

[56 62 68 74]

In [30]:
def math11(mat1, mat2):
  """
  Return the dot-products between each corresponding (same index) column in mat1 and mat2
  """
  return None

In [31]:
mat = np.arange(16).reshape((4, 4))
print(math11(mat,mat.T))

None


### Expected value

[ 56 174 324 506]