## Some math in python

Complete the code in the functions math1-math12 below.


In [1]:
import numpy as np


In [2]:
def math1(mat):
  """
  Square each value in mat separatly and return the result
  """
  return mat**2

In [3]:
mat = np.arange(16).reshape((4, 4))
print(math1(mat))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


### Expected output  
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [4]:
def math2(mat):
  """
  Return the sum of all the values in mat
  """
  return mat.sum()


In [5]:
mat = np.arange(16).reshape((4, 4))
print(math2(mat))

120


### Expected output

120


In [6]:
def math3(mat):
  """
  Return the sum of each row in mat
  """
  #return mat.sum(0)
  return(mat.sum(1))

In [8]:
mat = np.arange(16).reshape((4, 4))
#print(mat)
print(math3(mat)) 

[ 6 22 38 54]


### Expected output

[ 6 22 38 54]

In [9]:
def math4(mat):
  """
  Return a scaled version of mat, so that it sums to 1
  """
  return mat/np.sum(mat.astype(np.float))


In [10]:
mat = np.arange(16).reshape((4, 4))
print(math4(mat))

[[ 0.          0.00833333  0.01666667  0.025     ]
 [ 0.03333333  0.04166667  0.05        0.05833333]
 [ 0.06666667  0.075       0.08333333  0.09166667]
 [ 0.1         0.10833333  0.11666667  0.125     ]]


### Expected output

[[ 0.          0.00833333  0.01666667  0.025     ]
 [ 0.03333333  0.04166667  0.05        0.05833333]
 [ 0.06666667  0.075       0.08333333  0.09166667]
 [ 0.1         0.10833333  0.11666667  0.125     ]]

In [11]:
def math5(mat, v):
  """
  Element-wise multiply each column in mat with vector v
  """
  return mat*v[:, np.newaxis]

In [12]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math5(mat,vec))

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


### Expected output

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]

In [13]:
def math6(mat, v):
  """
  Element-wise multiply each row in mat with vector v
  """
  return mat*v[np.newaxis]


In [14]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math6(mat,vec))

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]


### Expected output

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]

In [15]:

def math7(mat, v):
  """
  Matrix multiply matrix m with vector v
  """
  return mat.dot(v)

In [16]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math7(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [19]:
def math8(mat):
  """
  Return the inverse matrix of mat
  """
  return np.linalg.inv(mat)


In [20]:
mat = np.array([[4, 7], [2, 6]])
print(math8(mat))

[[ 0.6 -0.7]
 [-0.2  0.4]]


### Expected output

[[ 0.6 -0.7]
 [-0.2  0.4]]
 

In [22]:
def math9(mat, v):
  """
  Return the dot-product between each row in mat and v
  """
  return mat.dot(v)

In [23]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math9(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [24]:
def math10(mat, v):
  """
  Return the dot-product between each column in mat and v
  """
  return mat.T.dot(v)


In [25]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math10(mat,vec))

[56 62 68 74]


### Expected output

[56 62 68 74]

In [26]:
def math11(mat1, mat2):
  """
  Return the dot-products between each corresponding (same index) column in mat1 and mat2
  """
  return (mat1*mat2).sum(1)

In [27]:
mat = np.arange(16).reshape((4, 4))
print(math11(mat,mat.T))

[ 56 174 324 506]


### Expected value

[ 56 174 324 506]